import React, { useState, useEffect } from "react";
import constant from "../../../env";
import { CallApi } from "../../../api";
import { toast } from "react-toastify";
import {
  FiDownload,
  FiDollarSign,
  FiGift,
  FiClock,
  FiCreditCard,
  FiTrendingUp,
  FiCheckCircle,
  FiAlertCircle,
} from "react-icons/fi";

const EmployeeSalary = () => {
  const [loading, setLoading] = useState(true);
  const [salaryData, setSalaryData] = useState(null);

  useEffect(() => {
    fetchEmployeeSalaryData();
  }, []);

  const fetchEmployeeSalaryData = async () => {
    try {
      setLoading(true);
      const apiUrl =
        constant.API.EMPLOYEE.SALARY_DASHBOARD ||
        "/api/employee/salary/dashboard";

      const response = await CallApi(apiUrl, "GET");

      if (response && response.status) {
        setSalaryData(response.data);
      } else {
        toast.error(response?.message || "Failed to load salary details");
      }
    } catch (error) {
      console.error("Employee Salary Fetch Error:", error);
      toast.error("Error fetching salary details");
    } finally {
      setLoading(false);
    }
  };

  // Currency Formatter Utility
  const formatCurrency = (val) => {
    if (val === undefined || val === null) return "₹0";
    const num = parseFloat(val);
    return `₹${num.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
  };

  const hasStructure = salaryData?.hasStructure ?? true;
  const summary = salaryData?.summary || {};
  const currentMonthData = summary.currentMonth || {};
  const historyList = salaryData?.history || [];
  const currentMonthName = salaryData?.currentMonth || "Current Month";

  // Target Achievement % Calculation
  const basicSalaryNum = parseFloat(summary.basicSalary || 0);
  const targetNum = parseFloat(summary.monthlyTarget || 0);
  const achievedNum = parseFloat(currentMonthData.achievedPremium || 0);
  const targetPercent =
    targetNum > 0 ? Math.min(100, Math.round((achievedNum / targetNum) * 100)) : 0;

  const grossEarnings =
    basicSalaryNum +
    parseFloat(currentMonthData.incentive || 0) +
    parseFloat(currentMonthData.bonus || 0);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64 text-slate-400 font-medium">
        Loading salary details...
      </div>
    );
  }

  if (!hasStructure) {
    return (
      <div className="bg-white p-8 rounded-2xl border border-slate-100 text-center space-y-3">
        <FiAlertCircle className="mx-auto text-amber-500" size={40} />
        <h3 className="text-lg font-bold text-slate-800">No Salary Structure Found</h3>
        <p className="text-xs text-slate-400 max-w-sm mx-auto">
          Your salary structure hasn't been generated by admin yet. Please contact HR or Management.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6 select-none font-sans">
      {/* HEADER SECTION */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">
            My Salary & Earnings
          </h1>
          <p className="text-slate-400 text-sm mt-0.5 font-medium">
            Salary Breakdown for <strong className="text-slate-600">{currentMonthName}</strong>
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-teal-50 text-[#00a896] flex items-center justify-center shrink-0">
            <FiCreditCard size={22} />
          </div>
          <div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
              Net Payable
            </p>
            <h3 className="text-xl font-bold text-slate-900 mt-0.5">
              {formatCurrency(currentMonthData.netSalary)}
            </h3>
            <span className="text-[10px] font-bold text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-md border border-indigo-100 inline-block mt-1">
              Status: {currentMonthData.status || "Generated"}
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0">
            <FiDollarSign size={22} />
          </div>
          <div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
              Basic Salary
            </p>
            <h3 className="text-xl font-bold text-slate-900 mt-0.5">
              {formatCurrency(summary.basicSalary)}
            </h3>
            <span className="text-[10px] font-semibold text-slate-400 inline-block mt-1">
              Fixed Monthly
            </span>
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
            <FiGift size={22} />
          </div>
          <div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
              Incentives
            </p>
            <h3 className="text-xl font-bold text-slate-900 mt-0.5">
              {formatCurrency(currentMonthData.incentive)}
            </h3>
            <span className="text-[10px] font-semibold text-slate-400 inline-block mt-1">
              Target Based
            </span>
          </div>
        </div>

        {/* Card 4: Late Deductions */}
        <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-amber-50 text-amber-600 flex items-center justify-center shrink-0">
            <FiClock size={22} />
          </div>
          <div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
              Late Deduction
            </p>
            <h3 className="text-xl font-bold text-slate-900 mt-0.5">
              {formatCurrency(currentMonthData.lateDeduction)}
            </h3>
            <span className="text-[10px] font-bold text-rose-500 bg-rose-50 px-1.5 py-0.5 rounded-md border border-rose-100 inline-block mt-1">
              {currentMonthData.lateCount || 0} Late Days
            </span>
          </div>
        </div>
      </div>

      {/* 2. MAIN SECTION: BREAKDOWN & TARGET PERFORMANCE */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* LEFT: DETAILED SALARY BREAKDOWN (7 Cols) */}
        <div className="lg:col-span-7 bg-white rounded-2xl border border-slate-100 shadow-sm p-6 space-y-5">
          <div className="flex items-center justify-between border-b border-slate-100 pb-4">
            <div>
              <h3 className="text-base font-bold text-slate-800 tracking-tight">
                Salary Breakdown
              </h3>
              <p className="text-xs text-slate-400 font-medium">
                Detailed earnings and deductions for {currentMonthName}
              </p>
            </div>
            <button className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs px-4 py-2 rounded-xl flex items-center gap-2 transition shadow-sm cursor-pointer">
              <FiDownload size={14} /> Payslip PDF
            </button>
          </div>

          {/* Earnings Table */}
          <div className="space-y-3">
            <div className="flex justify-between text-xs font-bold text-emerald-600 border-b border-slate-100 pb-1.5">
              <span>EARNINGS</span>
              <span>AMOUNT</span>
            </div>
            <div className="flex justify-between text-xs text-slate-600 font-medium">
              <span>Basic Salary</span>
              <span className="font-semibold text-slate-800">
                {formatCurrency(summary.basicSalary)}
              </span>
            </div>
            <div className="flex justify-between text-xs text-slate-600 font-medium">
              <span>Incentive (Target Achieved)</span>
              <span className="font-semibold text-slate-800">
                {formatCurrency(currentMonthData.incentive)}
              </span>
            </div>
            <div className="flex justify-between text-xs text-slate-600 font-medium">
              <span>Bonus / Performance Allowance</span>
              <span className="font-semibold text-slate-800">
                {formatCurrency(currentMonthData.bonus)}
              </span>
            </div>
            <div className="flex justify-between text-xs font-bold text-emerald-600 pt-2 border-t border-slate-100">
              <span>Total Gross Earnings</span>
              <span>{formatCurrency(grossEarnings)}</span>
            </div>
          </div>

          <div className="space-y-3 pt-2">
            <div className="flex justify-between text-xs font-bold text-rose-500 border-b border-slate-100 pb-1.5">
              <span>DEDUCTIONS</span>
              <span>AMOUNT</span>
            </div>
            <div className="flex justify-between text-xs text-slate-600 font-medium">
              <span>Late Attendance ({currentMonthData.lateCount || 0} Days)</span>
              <span className="font-semibold text-slate-800">
                {formatCurrency(currentMonthData.lateDeduction)}
              </span>
            </div>
            <div className="flex justify-between text-xs font-bold text-rose-500 pt-2 border-t border-slate-100">
              <span>Total Deductions</span>
              <span>{formatCurrency(currentMonthData.lateDeduction)}</span>
            </div>
          </div>

          <div className="flex justify-between items-center bg-teal-50/50 p-4 rounded-xl border border-teal-100 mt-4">
            <div>
              <span className="font-bold text-xs uppercase tracking-wider text-slate-500 block">
                Net Take-Home Salary
              </span>
              <span className="text-[11px] text-slate-400 font-medium">
                (Gross Earnings - Total Deductions)
              </span>
            </div>
            <span className="font-extrabold text-2xl text-[#00a896]">
              {formatCurrency(currentMonthData.netSalary)}
            </span>
          </div>
        </div>

        <div className="lg:col-span-5 bg-white rounded-2xl border border-slate-100 shadow-sm p-6 space-y-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
              <FiTrendingUp className="text-[#00a896]" size={18} />
              <h3 className="text-base font-bold text-slate-800 tracking-tight">
                Monthly Target vs Achievement
              </h3>
            </div>

            <div className="mt-5 space-y-4">
              <div className="flex justify-between items-end">
                <div>
                  <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                    Achieved Premium
                  </p>
                  <p className="text-lg font-extrabold text-emerald-600 mt-0.5">
                    {formatCurrency(currentMonthData.achievedPremium)}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                    Target Goal
                  </p>
                  <p className="text-sm font-bold text-slate-700 mt-0.5">
                    {formatCurrency(summary.monthlyTarget)}
                  </p>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="space-y-1.5">
                <div className="w-full bg-slate-100 h-3 rounded-full overflow-hidden">
                  <div
                    className="bg-[#00a896] h-full rounded-full transition-all duration-500"
                    style={{ width: `${targetPercent}%` }}
                  ></div>
                </div>
                <div className="flex justify-between text-[11px] font-bold text-slate-400">
                  <span>{targetPercent}% Completed</span>
                  <span>
                    {targetPercent >= 100 ? "Target Unlocked! 🎉" : "In Progress"}
                  </span>
                </div>
              </div>
            </div>

            <div className="mt-6 bg-slate-50 p-4 rounded-xl border border-slate-200/80 flex items-center justify-between">
              <div>
                <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  Yearly Total Earnings
                </p>
                <p className="text-base font-bold text-slate-800 mt-0.5">
                  {formatCurrency(salaryData?.yearlyTotal)}
                </p>
              </div>
              <span className="text-xs px-2.5 py-1 rounded-lg font-bold bg-teal-50 text-[#00a896] border border-teal-100">
                2026 YTD
              </span>
            </div>
          </div>

          <div className="pt-4 border-t border-slate-100">
            <span className="text-[11px] text-slate-400 font-semibold flex items-center justify-center gap-1">
              <FiCheckCircle size={13} className="text-emerald-500" /> Salary
              disbursement verified by HR & Accounts
            </span>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
          <h3 className="text-base font-bold text-slate-800 tracking-tight">
            Past Salary History
          </h3>
          <span className="text-xs text-slate-400 font-medium">
            Archived Payslips
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[650px]">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-100 text-[10px] font-bold tracking-widest text-slate-400 uppercase">
                <th className="py-3.5 px-4">Period</th>
                <th className="py-3.5 px-4">Basic (₹)</th>
                <th className="py-3.5 px-4">Incentive (₹)</th>
                <th className="py-3.5 px-4">Late Deduction (₹)</th>
                <th className="py-3.5 px-4">Bonus (₹)</th>
                <th className="py-3.5 px-4">Net Salary (₹)</th>
                <th className="py-3.5 px-4">Status</th>
                <th className="py-3.5 px-4 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-xs font-medium text-slate-700">
              {historyList.length === 0 && (
                <tr>
                  <td colSpan="8" className="text-center py-8 text-gray-400 font-medium">
                    No past salary records available.
                  </td>
                </tr>
              )}

              {historyList.map((item, idx) => (
                <tr key={idx} className="hover:bg-slate-50/80 transition">
                  <td className="py-3.5 px-4 font-bold text-slate-900">
                    {item.month}
                  </td>
                  <td className="py-3.5 px-4 font-medium text-slate-700">
                    {formatCurrency(item.basicSalary)}
                  </td>
                  <td className="py-3.5 px-4 text-emerald-600 font-bold">
                    {formatCurrency(item.incentive)}
                  </td>
                  <td className="py-3.5 px-4 text-rose-500 font-bold">
                    {formatCurrency(item.lateDeduction)}
                  </td>
                  <td className="py-3.5 px-4 text-slate-700 font-medium">
                    {formatCurrency(item.bonus)}
                  </td>
                  <td className="py-3.5 px-4 font-bold text-slate-900">
                    {formatCurrency(item.netSalary)}
                  </td>
                  <td className="py-3.5 px-4">
                    <span className="text-[10px] px-2.5 py-0.5 rounded-lg font-bold tracking-wide bg-indigo-50 text-indigo-700 border border-indigo-100">
                      {item.status || "Generated"}
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-center">
                    <button
                      title="Download Payslip"
                      className="p-1.5 text-indigo-600 hover:bg-indigo-50 rounded-lg transition"
                    >
                      <FiDownload size={15} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default EmployeeSalary;